version: "3.7"
services:
  db:
    image: postgres:12
    container_name: InsuranceDB
    environment:
      POSTGRES_USER: insurance
      POSTGRES_PASSWORD: password
      POSTGRES_DB: insurance
    ports:
      - "5433:5432"
    volumes:
      - ./db:/var/lib/postgresql/data